# Generated by Django 5.0.4 on 2024-05-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_remove_bid_bidded_listings_bid_listing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="removed",
            field=models.BooleanField(default=False),
        ),
    ]
