# Generated by Django 5.0.6 on 2024-05-15 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_listing_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="removed",
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="removed",
        ),
    ]
